<?php
/*
 * This is custom field.
 *
 * @package BOUTiQ
 */

/*--------------------------------------------------------------
  custom field
--------------------------------------------------------------*/
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_664c21a8b8924',
        'title' => 'コンテンツ',
        'fields' => array(
            array(
                'key' => 'field_664c361226be0',
                'label' => 'コンテンツブロック',
                'name' => 'content_block',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_664c367526be2',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'btn_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_664c367526be2',
                        'label' => 'コンテンツ名',
                        'name' => 'content_name',
                        'type' => 'text',
                        'instructions' => 'この項目は出力されません。',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_664c350126bdf',
                        'label' => 'ブロックデザインタイプ',
                        'name' => 'block_design_type',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'original' => 'オリジナルデザイン',
                            'news' => 'お知らせを表示',
                            'form01' => 'フォーム01',
                            'form02' => 'フォーム02',
                            'form03' => 'フォーム03',
                            'form04' => 'フォーム04',
                            'design01' => 'デザイン01',
                            'design02' => 'デザイン02',
                            'design03' => 'デザイン03',
                            'design04' => 'デザイン04',
                            'design05' => 'デザイン05',
                            'design06' => 'デザイン06',
                            'design07' => 'デザイン07',
                            'design08' => 'デザイン08',
                            'design09' => 'デザイン09',
                            'design10' => 'デザイン10',
                            'design11' => 'デザイン11',
                            'design12' => 'デザイン12',
                            'design13' => 'デザイン13',
                            'design14' => 'デザイン14',
                            'design15' => 'デザイン15',
                            'design16' => 'デザイン16',
                            'design17' => 'デザイン17',
                            'design18' => 'デザイン18',
                            'design19' => 'デザイン19',
                            'design20' => 'デザイン20',
                            'flow01' => 'フロー01',
                            'flow02' => 'フロー02',
                            'flow03' => 'フロー03',
                            'flow04' => 'フロー04',
                            'company01' => '会社概要のみ',
                            'company02' => '会社概要のみ（タイトル左）',
                            'company03' => '沿革',
                            'company04' => '沿革2カラム',
                            'company05' => '会社概要/沿革2カラム',
                            'faq01' => 'よくある質問01',
                            'faq02' => 'よくある質問02',
                            'faq03' => 'よくある質問03',
                            'loop01' => 'ループ01',
                            'lead01' => 'リード01（横幅100%）',
                            'lead02' => 'リード02（コンテンツエリア100%）',
                            'lead03' => 'リード03（２カラム横幅100%）',
                            'lead04' => 'リード04（２カラムコンテンツ幅）',
                            'lead05' => 'リード05（２カラムコンテンツ幅100%余白あり）',
                            'lead06' => 'リード06（3カラム横幅100%）',
                            'lead07' => 'リード07（3カラムコンテンツ幅）',
                            'lead08' => 'リード08（3カラムコンテンツ幅100%余白あり）',
                            'cta01' => 'CTA01',
                            'cta02' => 'CTA02',
                            'cta03' => 'CTA03',
                            'cta04' => 'CTA04',
                            'cta05' => 'CTA05',
                            'rule01' => '規約',
                            'rule02' => '規約（背景カード）',
                            'bg01' => '画像のみ01（横幅100%）',
                            'bg02' => '画像のみ02（コンテンツ幅）',
                            'bg03' => '画像のみ03（横幅100%・高さ固定）',
                            'bg04' => '画像のみ04（コンテンツ幅・高さ固定）',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_66cedb59476e6',
                        'label' => 'ブロックタイトル',
                        'name' => 'block_title',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'br',
                    ),
                    array(
                        'key' => 'field_664c36d626be3',
                        'label' => 'ブロックサブタイトル',
                        'name' => 'block_subtitle',
                        'type' => 'textarea',
                        'instructions' => 'オリジナルデザインを選択した場合は、ここにslug（英数字）を追加し、pageディレクトリに【content-page名_slug名.php】ファイルを作成してカスタマイズコードを記載してください。（例：HOMEページのworksコンテンツなら【content-home_works.php】）',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'br',
                    ),
                    array(
                        'key' => 'field_664c37b626be8',
                        'label' => 'タイトル画像・背景画像',
                        'name' => 'block_title_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_66b462737ab2b',
                        'label' => 'ブロックタイトル色',
                        'name' => 'block_title_color',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_664c362b26be1',
                        'label' => 'ブロック背景色',
                        'name' => 'block_bg_color',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_66687d24e8fc1',
                        'label' => 'ブロック内のテキスト色',
                        'name' => 'block_text_color',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#393939',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                    ),
                    array(
                        'key' => 'field_66ced053f972b',
                        'label' => 'ブロック画像・背景画像',
                        'name' => 'block_bg_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_664c371726be4',
                        'label' => '繰り返しパーツ',
                        'name' => 'block_parts',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => 'field_664c374326be5',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'row',
                        'btn_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_664c374326be5',
                                'label' => 'パーツタイトル',
                                'name' => 'block_parts_title',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 2,
                                'new_lines' => 'br',
                            ),
                            array(
                                'key' => 'field_664c3acece20b',
                                'label' => 'パーツサブタイトル',
                                'name' => 'block_parts_subtitle',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 2,
                                'new_lines' => 'br',
                            ),
                            array(
                                'key' => 'field_664c378d26be7',
                                'label' => 'パーツ説明テキスト',
                                'name' => 'block_parts_text',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                            array(
                                'key' => 'field_664c376326be6',
                                'label' => 'パーツ画像',
                                'name' => 'block_parts_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_666bf62abd705',
                                'label' => 'パーツ動画/MAP/会社概要・沿革',
                                'name' => 'block_parts_editor',
                                'type' => 'wysiwyg',
                                'instructions' => '画像ではなく動画を挿入したい場合、GoogleMapのURL、会社概要/会社沿革等で使用します。
    テキストカラーのクラス【u-color__main：メインカラー】【u-color__accent：アクセントカラー】【u-color__base：ベースカラー】',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                            array(
                                'key' => 'field_664c37fb26be9',
                                'label' => 'パーツリンク',
                                'name' => 'block_parts_link_url',
                                'type' => 'text',
                                'instructions' => 'リンクを設置したい場合はURLを記入します',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_664c385026beb',
                                'label' => 'パーツテキスト',
                                'name' => 'block_parts_link_text',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_6668f122d4746',
                                'label' => 'パーツリンクデザイン',
                                'name' => 'block_parts_link_type',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'text' => 'テキストリンク',
                                    'btn' => 'ボタンリンク',
                                ),
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_66cf389dca340',
                        'label' => 'ブロックフリーエリア',
                        'name' => 'block_free_area',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-law.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;
